language: node_js
node_js: '4.2.1'
install:
  - npm install
before_script:
  - webpack --config webpack.prod.config.js
branches:
  only:
    - master
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: $ACCESS_ID
  secret_access_key:
    secure: $ACCESS_SECRET
  bucket: $BUCKET
  local-dir: build
  acl: public_read
  region: eu-central-1
  on:
    branch: master
    repo: kdrozdov/posts_frontend
